apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: parseforge
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: backend
          image: ghcr.io/nehadevarapalli/parseforge-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: parseforge-backend-secrets
                  key: ACCESS_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: parseforge-backend-secrets
                  key: SECRET_KEY
            - name: BUCKET_URL  
              valueFrom:
                secretKeyRef:
                  name: parseforge-backend-secrets
                  key: BUCKET_URL
            - name: LLAMAPARSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: parseforge-backend-secrets
                  key: LLAMAPARSE_API_KEY
            - name: fire_api
              valueFrom:
                secretKeyRef:
                  name: parseforge-backend-secrets
                  key: fire_api
            - name: ENVIRONMENT
              value: "production"
            - name: PORT
              value: "8000"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi" #Minimum guaranteed memory
            limits:
              cpu: "2000m"
              memory: "5Gi" #Maximum allowed memory
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: parseforge
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000  # cluster-internal port
      targetPort: 8000
  type: ClusterIP
